version: '3.7'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    container_name: app_ecommerce_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - db-data:/data/db
    networks:
      - network-data
    restart: always

  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: app_ecommerce_server
    ports:
      - '5000:5000'
    volumes:
      - .:/app/server
      - /app/server/node_modules
    depends_on:
      - mongodb
    networks:
      - network-data
    restart: always
    env_file:
      - ./server/.env

  admin-front:
    build:
      dockerfile: Dockerfile
      context: ./admin-front
    container_name: app_ecommerce_admin_front
    ports:
      - '3000:3000'
    volumes:
      - .:/app/admin-front
      - /app/admin-front/node_modules
    depends_on:
      - mongodb
    networks:
      - network-data
    restart: always

  user-front:
    build:
      dockerfile: Dockerfile
      context: ./user-front
    container_name: app_ecommerce_user_front
    ports:
      - '5173:5173'
    volumes:
      - .:/app/user-front
      - /app/user-front/node_modules
    depends_on:
      - mongodb
    networks:
      - network-data
    restart: always

volumes:
  db-data:

networks:
  network-data:
