name: Continous Integration

on:
  pull_request:
    branches: [ "master" ]

jobs:
  ci_verification:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
   
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name : Test Backend Service
      working-directory: ./server
      run: |
        npm i
        npm test

    - name : Test Admin Frontend Service
      working-directory: ./admin-front
      run: |
        npm i
        npm test
        npm run build --if-present

    - name : Test User Frontend Service
      working-directory: ./user-front
      run: |
        npm i
        npm test
        npm run build --if-present
